### ISSUE TITLE
我想修改虚拟设备的信息。这个功能是计划好的吗？

### ISSUE THREAD

**Issue by dream811** [CodingGay/BlackDex#102]
**在此写下你的问题**
![image](https://user-images.githubusercontent.com/45660446/223882860-ca9982af-426c-461b-a73e-5a237c9459f9.png)
我想修改虚拟设备的信息。

**Comment by xiaoyaomeng** [comment]
很高兴收到您的邮件，看到后将立即回复~Thank you~
