### ISSUE TITLE
AntiSplit-X 爱加密脱壳失败

### ISSUE THREAD

**Issue by wushidia** [CodingGay/BlackDex#21]
**描述错误**
AntiSplit-X [爱加密脱壳失败](https://wushidi.lanzoui.com/i41ekq3duwj)

**重现**
重现该行为的步骤:
1.选择从外部导入apk，脱壳
2.提示脱壳失败

**设备信息**
 - 设备: 小米9
 - Android版本: 11(Pixel Experience Plus 11）

**运行日志**

https://wushidi.lanzoui.com/ir0n3q3dxej

**其他说明**

**Comment by nnjun** [comment]
无必要的话请关闭深度脱壳，此次已dump出部分dex，由于修复过程中导致crash中断了dump
