### ISSUE TITLE
Jiagu 360 is unsupported

### ISSUE THREAD

**Issue by ZMODs** [CodingGay/BlackDex#23]
**Description error**
Unpack fail

![image](https://user-images.githubusercontent.com/64008639/122679297-95c1f180-d1ea-11eb-94fb-7b1f8543edd4.png)

**Reproduce**
1. Open BlackDex 32
2. Choose an app to dump

**Device Information**
  -Equipment: Memu emulator 
  -Android version: 7.1.1

**Run log**
[top.niunaijun.blackdexa32_logcat.txt](https://github.com/CodingGay/BlackDex/files/6682581/top.niunaijun.blackdexa32_logcat.txt)

**other instructions**
APK can be downloaded here https://drive.google.com/file/d/1YJ5fXiSdA8wg20s-Y54bWUuq7myD9Rp9/view

**Comment by nnjun** [comment]
This app has environment detection

**Comment by nnjun** [comment]
[BlackDex32-.apk.zip](https://github.com/CodingGay/BlackDex/files/6692054/BlackDex32-.apk.zip)

It's fixed. You can test it.

**Comment by linhua55** [comment]
cookie_   和 hook_开头的文件是重复的吗？ 应该选哪个？

**Comment by nnjun** [comment]
> cookie_ 和 hook_开头的文件是重复的吗？ 应该选哪个？

cookie_为最原始版本的脱壳，hook_是最新版支持的另一种脱壳方式。两者可能会有重复dex，两个都可以。后面的数字是dex的大小。一般相同的就是同一个

**Comment by nnjun** [comment]
Or you can download V3.0.0 from releases

**Comment by ZMODs** [comment]
Still fails on emulator but it works now on my phone

Here is log in case you wanna fix it
[top.niunaijun.blackdexa32_logcat.txt](https://github.com/CodingGay/BlackDex/files/6693001/top.niunaijun.blackdexa32_logcat.txt)

**Comment by nnjun** [comment]
try use your phone

**Comment by nnjun** [comment]
OK, I'll try to fix it
