### ISSUE TITLE
版本bug

### ISSUE THREAD

**Issue by su8052** [CodingGay/BlackDex#26]
**描述错误**
不背单词用2.0blackdex能脱全,用3.0blackdex只能把原先apk文件里显示的dex文件给脱出来其他的就没了

**重现**
重现该行为的步骤:
1.用2.0blackdex脱不背单词
2.用3.0blackdex脱不背单词

**设备信息**
 - 设备: [红米k30pro变焦版]
 - Android版本: [10]

**运行日志**
请提供运行时所有Logcat日志以便我们排查问题，如果您不是开发者请重现问题之后，提供手机存储：/Download/top.niunaijun.blackdex32(64)_logcat.txt 文件的内容，此内容重启应用将重置，请勿重启应用后才发送。

**其他说明**

**Comment by nnjun** [comment]
由于新版本加强功能崩溃导致无法成功，属于致命错误暂无法解决，可使用新版本在设置内进行开关加强功能

https://github.com/CodingGay/BlackDex/releases/tag/v3.1.0
