### ISSUE TITLE
MIUI 12.5 安卓11脱某APP不成功,用旧手机MIUI 11 安卓7可以成功

### ISSUE THREAD

**Issue by menggangaaa** [CodingGay/BlackDex#31]
**描述错误**
MIUI 12.5 安卓11脱某APP不成功,用旧手机MIUI 11 安卓7可以成功

**重现**
重现该行为的步骤:
![image](https://user-images.githubusercontent.com/30853468/124686884-78896480-df06-11eb-9778-2f6fd4f59416.png)

**设备信息**
 - 设备: [小米9 SE]
 - Android版本: [11]
 - MIUI版本: 12.5

**运行日志**
[top.niunaijun.blackdexa32_logcat.txt](https://github.com/CodingGay/BlackDex/files/6773636/top.niunaijun.blackdexa32_logcat.txt)

**其他说明**

**Comment by nnjun** [comment]
请使用3.1.0版本，关闭hook脱壳后重试一下

**Comment by menggangaaa** [comment]
试了一下 还是不行

**Comment by ZipperCode** [comment]
红米K30Pro - Android 11 - MIUI 12.5 
脱壳日志找不到libblackdex.so 文件

**Comment by nnjun** [comment]
> 红米K30Pro - Android 11 - MIUI 12.5 脱壳日志找不到libblackdex.so 文件

@ZipperCode 手动编译请make project一次再重新安装。
