### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by yj-jwds** [CodingGay/BlackDex#33]
**描述错误**
在3.1版本中脱爱加密的壳，开启hook脱不成功，不开会得到nop

**设备信息**
 - 设备: [小米10]
 - Android版本: [10]

**运行日志**
请提供运行时所有Logcat日志以便我们排查问题，如果您不是开发者请重现问题之后，提供手机存储：/Download/top.niunaijun.blackdex32(64)_logcat.txt 文件的内容，此内容重启应用将重置，请勿重启应用后才发送。

**其他说明**

**Comment by owen800q** [comment]
爱加密有反調試，脱不了的

**Comment by yj-jwds** [comment]
我在真机上通过数据滤镜可以隐藏root以及xp可以hook到dex但是脱出来都是nop

**Comment by nnjun** [comment]
一般会脱到一半挂掉的都是企业壳带有反调试。这种不在处理范围内。
