### ISSUE TITLE
修复DEX时部分类修复失败

### ISSUE THREAD

**Issue by rigo0** [CodingGay/BlackDex#35]
在尝试修复某个DEX的NOP指令时，有两个类修复失败。调用 getDeclaredMethods 时异常：“Failed resolution of: Ljavax/naming/directory/DirContext;”，改调用getMethods时正常，导致私有方法无法正常修复。

**Comment by nnjun** [comment]
按照你说的这个逻辑getMethods只能拿到公共方法，更不可能修复私有方法呀

**Comment by rigo0** [comment]
在getDeclaredMethods 报异常的情况下我才用getMethods去尝试的，也就是说getDeclaredMethods拿不到方法，而getMethods可以

**Comment by nnjun** [comment]
你可以加多一条流程，getDeclaredMethods的异常单独去捕获，当getDeclaredMethods处理完之后再处理getMethods。

**Comment by rigo0** [comment]
目前就是这样处理的，但是我想把所有的函数都修复好，正在尝试更换JDK版本，不知道是否有效

**Comment by nnjun** [comment]
这个我在新代码中补上了

> 你可以加多一条流程，getDeclaredMethods的异常单独去捕获，当getDeclaredMethods处理完之后再处理getMethods。
