### ISSUE TITLE
Can only dump 1 out of 18 dexes

### ISSUE THREAD

**Issue by KarmaMod** [CodingGay/BlackDex#36]
**Description error**
It can only dump 1 dex even it found 18 dexes

![image](https://user-images.githubusercontent.com/88159598/127647112-3a40d7b2-51aa-4efc-b33d-1ba8d751372c.png)

**Reproduce**
1. Install this APK https://drive.google.com/file/d/1NOB26YJbA3NxvNaPqQiGIvPqFyrOyp_g/view
2. Dump via BlackDex 

**Device Information**
  -Equipment: Nox Player 9
  -Android version: 9

**Run log**
[top.niunaijun.blackdexa32_logcat.txt](https://github.com/CodingGay/BlackDex/files/6907219/top.niunaijun.blackdexa32_logcat.txt)

**other instructions**

**Comment by nnjun** [comment]
VmCore  : Open dex error Failure to verify dex file '': Bad header size: 136d expected 112d

dex is bad
