### ISSUE TITLE
tantan_4.7.7.1.apk 脱壳报错

### ISSUE THREAD

**Issue by skfly007** [CodingGay/BlackDex#42]
**描述错误**
![image](https://user-images.githubusercontent.com/12248308/128836833-7df291b0-c150-4d0a-a4d5-ebf4b4106b43.png)

**重现**
重现该行为的步骤:
打开磁盘上的apk文件

**设备信息**
 - 设备: Pixel4
 - Android版本: 11

**Comment by nnjun** [comment]
请提供日志
