### ISSUE TITLE
Can only dump stub dex

### ISSUE THREAD

**Issue by KarmaMod** [CodingGay/BlackDex#45]
**Description error**
APK is protected by aegis protection, BlackDex can only dump stub dex. I have tried dump with hook enabled
Can you support it?

**Reproduce**
1. Install the APK
2. Dump using Blackdex

**Device Information**
  -Equipment: [Google Pixel]
  -Android version: [11]

**Run log**
[top.niunaijun.blackdexa32_logcat.txt](https://github.com/CodingGay/BlackDex/files/7082970/top.niunaijun.blackdexa32_logcat.txt)

**APK**
https://drive.google.com/file/d/1epSv8c7QlMj26Z8LfYKwqZ3p3XUOvEI-/view

**Comment by HighMod** [comment]
Ok, i successfully dump aegis0.dat manually from memory, but would be great if Blackdex supported it
