### ISSUE TITLE
when the  man tried to shelling an app,there is an error alert.

### ISSUE THREAD

**Issue by PythonManEnjoyLife** [CodingGay/BlackDex#49]
**描述错误**
简要说明遇到了什么问题
准备将闽政通App脱壳时，发现不允许。所有的错误都是通用错误，不知道具体原因，是因为加密措施吗？

**重现**
重现该行为的步骤:
1.通过blackdex32打开闽政通app
2.软件配置，深度脱壳。

**设备信息**
 - 设备: [华为nova8]
 - Android版本: [10]，实际是鸿蒙2.0 但是向下兼容所以说是andriod10也对。

**运行日志**
请提供运行时所有Logcat日志以便我们排查问题，如果您不是开发者请重现问题之后，提供手机存储：/Download/top.niunaijun.blackdex32(64)_logcat.txt 文件的内容，此内容重启应用将重置，请勿重启应用后才发送。

**其他说明**

**Comment by nnjun** [comment]
这种政府相关的基本都是企业加固
