### ISSUE TITLE
樊登读书会不能成功脱壳

### ISSUE THREAD

**Issue by barcelona-messi** [CodingGay/BlackDex#50]
下载链接：https://gyxz2.243ty.com/io.dushu.fandengreader.apk

**描述错误**
樊登读书会是爱加密加固的

**设备信息**
 - 设备: 一加7Pro
 - Android版本: 11

**其他说明**
![image](https://user-images.githubusercontent.com/16136063/134794040-24b20063-4602-4577-961d-705b5b66d628.png)

**Comment by owen800q** [comment]
@barcelona-messi 
是如何解決的？
