### ISSUE TITLE
脱爱加密失败

### ISSUE THREAD

**Issue by caicaidarenya** [CodingGay/BlackDex#55]
**描述错误**
简要说明遇到了什么问题

**重现**
重现该行为的步骤:
1.xxx
2.xxx

**设备信息**
 - 设备: [小米10]
 - Android版本: [10]

**运行日志**
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/dipper/dipper:10/QKQ1.190828.002/20.9.4:user/release-keys'
Revision: '0'
ABI: 'arm'
Timestamp: 2021-10-20 22:30:59+0800
pid: 31077, tid: 31077, name: .blackdexa32:p0  >>> top.niunaijun.blackdexa32:p0 <<<
uid: 11399
signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0xefc87004 (*pc=0xf010f8df)
    r0  e6b94a64  r1  f342e470  r2  ffda2c84  r3  ffda2d38
    r4  f342e470  r5  efc87001  r6  00000000  r7  ffda2c10
    r8  f344b2c0  r9  00000013  r10 00000000  r11 ffffffff
    ip  ffda2d38  sp  ffda2c00  lr  ab5e95bb  pc  efc87004

backtrace:
    NOTE: Function names and BuildId information is missing for some frames due
    NOTE: to unreadable libraries. For unwinds of apps, only shared libraries
    NOTE: found under the lib/ directory are readable.
      #00 pc 00000004  <anonymous:efc87000>
      #01 pc 0005c5b9  /data/data/top.niunaijun.blackdexa32/virtual/data/app/com.wondertek.miguaikan/lib/libblackdex.so
      #02 pc 000fae71  /apex/com.android.runtime/lib/libart.so (art::ClassLinker::LoadClass(art::Thread*, art::DexFile const&, art::dex::ClassDef const&, art::Handle<art::mirror::Class>)+628) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #03 pc 000f7cd9  /apex/com.android.runtime/lib/libart.so (art::ClassLinker::DefineClass(art::Thread*, char const*, unsigned int, art::Handle<art::mirror::ClassLoader>, art::DexFile const&, art::dex::ClassDef const&)+616) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #04 pc 001165ad  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0xfd000) (_ZN3art27VisitClassLoaderDexElementsIZNS_24VisitClassLoaderDexFilesIZNS_24VisitClassLoaderDexFilesIZNS_11ClassLinker38FindClassInBaseDexClassLoaderClassPathERNS_33ScopedObjectAccessAlreadyRunnableEPKcjNS_6HandleINS_6mirror11ClassLoaderEEEE4$_31EEvS5_SB_T_EUlPKNS_7DexFileEPPvE_SH_EET0_S5_SB_SD_SK_EUlNS_6ObjPtrINS9_6ObjectEEESI_E_SH_EESK_S5_SB_SD_SK_+440) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #05 pc 000f7351  /apex/com.android.runtime/lib/libart.so (art::ClassLinker::FindClassInBaseDexClassLoader(art::ScopedObjectAccessAlreadyRunnable&, art::Thread*, char const*, unsigned int, art::Handle<art::mirror::ClassLoader>, art::ObjPtr<art::mirror::Class>*)+464) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #06 pc 0031b361  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0xfd000) (art::VMClassLoader_findLoadedClass(_JNIEnv*, _jclass*, _jobject*, _jstring*)+428) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #07 pc 0005a1f7  /data/app/top.niunaijun.blackdexa32-z8vPlT5hctRkXB-8u4kVsg==/lib/arm/libblackdex.so (new_findLoadedClass(_JNIEnv*, _jobject*, _jobject*, _jstring*)+134) (BuildId: 9d92e13dacd181be0ce8e476c235743e1b57630e)
      #08 pc 002d07cb  /system/framework/arm/boot-core-libart.oat (art_jni_trampoline+130) (BuildId: e455336f5e26e0eb8d6917c7384d11b967db818f)
      #09 pc 00249dc9  /system/framework/arm/boot.oat (java.lang.ClassLoader.loadClass+88) (BuildId: 52d5c17fe90528589dd150bf3e6b5733704debeb)
      #10 pc 00249d59  /system/framework/arm/boot.oat (java.lang.ClassLoader.loadClass+40) (BuildId: 52d5c17fe90528589dd150bf3e6b5733704debeb)
      #11 pc 0090b117  /system/framework/arm/boot-framework.oat (android.app.AppComponentFactory.instantiateApplication+46) (BuildId: 0709797f86c834951e731e9ebaf31386cf159b08)
      #12 pc 000d7bc5  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #13 pc 00439fe5  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0xfd000) (art_quick_invoke_stub+252) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #14 pc 000dffeb  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+178) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #15 pc 00213779  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0xfd000) (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+280) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #16 pc 0020f091  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0xfd000) (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+716) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #17 pc 0042fd1b  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0xfd000) (MterpInvokeSuper+1278) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #18 pc 000d2894  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_super+20) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #19 pc 0001baa0  /data/app/com.wondertek.miguaikan-LZVKa6hSU2qdB_3FezBhTQ==/oat/arm/base.vdex (s.h.e.l.l.A.instantiateApplication+28)
      #20 pc 001eea11  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0xfd000) (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.6078130102404447026+192) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #21 pc 001f3203  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0xfd000) (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+126) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #22 pc 00423ac9  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0xfd000) (artQuickToInterpreterBridge+852) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #23 pc 000dc5a1  /apex/com.android.runtime/lib/libart.so (art_quick_to_interpreter_bridge+32) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #24 pc 0092a301  /system/framework/arm/boot-framework.oat (android.app.Instrumentation.newApplication+88) (BuildId: 0709797f86c834951e731e9ebaf31386cf159b08)
      #25 pc 001d57ef  /data/app/top.niunaijun.blackdexa32-z8vPlT5hctRkXB-8u4kVsg==/oat/arm/base.odex (top.niunaijun.blackbox.fake.delegate.AppInstrumentation.newApplication+654)
      #26 pc 00934b69  /system/framework/arm/boot-framework.oat (android.app.LoadedApk.makeApplication+424) (BuildId: 0709797f86c834951e731e9ebaf31386cf159b08)
      #27 pc 000d7bc5  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #28 pc 00439fe5  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0xfd000) (art_quick_invoke_stub+252) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #29 pc 000dffeb  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+178) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #30 pc 00377b03  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0xfd000) (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+54) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #31 pc 00378dfd  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0xfd000) (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned int)+832) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #32 pc 003248af  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0xfd000) (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+30) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #33 pc 005f91e7  /system/framework/arm/boot.oat (art_jni_trampoline+110) (BuildId: 52d5c17fe90528589dd150bf3e6b5733704debeb)
      #34 pc 001d0071  /data/app/top.niunaijun.blackdexa32-z8vPlT5hctRkXB-8u4kVsg==/oat/arm/base.odex (reflection.MirrorReflection$MethodWrapper.call+80)
      #35 pc 001edc2d  /data/app/top.niunaijun.blackdexa32-z8vPlT5hctRkXB-8u4kVsg==/oat/arm/base.odex (top.niunaijun.blackbox.app.BActivityThread.handleBindApplication+1996)
      #36 pc 001ee363  /data/app/top.niunaijun.blackdexa32-z8vPlT5hctRkXB-8u4kVsg==/oat/arm/base.odex (top.niunaijun.blackbox.app.BActivityThread.bindApplication+362)
      #37 pc 001d60ab  /data/app/top.niunaijun.blackdexa32-z8vPlT5hctRkXB-8u4kVsg==/oat/arm/base.odex (top.niunaijun.blackbox.fake.service.HCallbackProxy.handleLaunchActivity+618)
      #38 pc 001d6405  /data/app/top.niunaijun.blackdexa32-z8vPlT5hctRkXB-8u4kVsg==/oat/arm/base.odex (top.niunaijun.blackbox.fake.service.HCallbackProxy.handleMessage+756)
      #39 pc 01387c17  /system/framework/arm/boot-framework.oat (android.os.Handler.dispatchMessage+110) (BuildId: 0709797f86c834951e731e9ebaf31386cf159b08)
      #40 pc 0138ebfd  /system/framework/arm/boot-framework.oat (android.os.Looper.loop+1340) (BuildId: 0709797f86c834951e731e9ebaf31386cf159b08)
      #41 pc 00bfb4a5  /system/framework/arm/boot-framework.oat (android.app.ActivityThread.main+756) (BuildId: 0709797f86c834951e731e9ebaf31386cf159b08)
      #42 pc 000d7bc5  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #43 pc 0043a0f9  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0xfd000) (art_quick_invoke_static_stub+248) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #44 pc 000dffff  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+198) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #45 pc 00377b03  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0xfd000) (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+54) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #46 pc 00378dfd  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0xfd000) (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned int)+832) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #47 pc 003248af  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0xfd000) (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+30) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #48 pc 005f91e7  /system/framework/arm/boot.oat (art_jni_trampoline+110) (BuildId: 52d5c17fe90528589dd150bf3e6b5733704debeb)
      #49 pc 01d784c3  /system/framework/arm/boot-framework.oat (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+114) (BuildId: 0709797f86c834951e731e9ebaf31386cf159b08)
      #50 pc 01d92ff9  /system/framework/arm/boot-framework.oat (com.android.internal.os.ZygoteInit.main+1888) (BuildId: 0709797f86c834951e731e9ebaf31386cf159b08)
      #51 pc 000d7bc5  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #52 pc 0043a0f9  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0xfd000) (art_quick_invoke_static_stub+248) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #53 pc 000dffff  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+198) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #54 pc 00377b03  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0xfd000) (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+54) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #55 pc 00377943  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0xfd000) (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+290) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #56 pc 002c12c1  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0xfd000) (art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+460) (BuildId: 6c13a6ecaf0bacb367a77812643fdc62)
      #57 pc 000876b1  /system/lib/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+28) (BuildId: 03e20fa815df7c5d01bc52e73f6a8d7b)
      #58 pc 00089d03  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+546) (BuildId: 03e20fa815df7c5d01bc52e73f6a8d7b)
      #59 pc 000023b5  /system/bin/app_process32 (main+880) (BuildId: 2f3784c7a0f560b2794b1696db586626)
      #60 pc 0005ab61  /apex/com.android.runtime/lib/bionic/libc.so (__libc_init+68) (BuildId: 8a332f5ddfdfaa762c88336c550e7e8b)
      #61 pc 0000202f  /system/bin/app_process32 (_start_main+38) (BuildId: 2f3784c7a0f560b2794b1696db586626)
      #62 pc 00004456  <anonymous:f39bb000>
~~~

**其他说明**

**Comment by nnjun** [comment]
这个不确定是不是跟一个hook有关，请提供样本。

**Comment by caicaidarenya** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by caicaidarenya** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by mstfamoyyeheiiehgh-hue** [comment]
https://www.facebook.com/mstfa . mosa.921

**Comment by mstfamoyyeheiiehgh-hue** [comment]
soso metfa 095590@gmail.com
