### ISSUE TITLE
脱壳失败

### ISSUE THREAD

**Issue by NorColumba** [CodingGay/BlackDex#58]
**在此写下你的问题**
样本双进程守护的，在frida也遇到过 log如下
12-05 12:48:50.037 28329 28329 W .blackdexa32:p: DexFile /data/user/0/top.niunaijun.blackdexa32/code_cache/1638679730036.dex is in boot class path but is not in a known location
12-05 12:48:50.107  1619 10094 I ActivityTaskManager: START u0 {flg=0x18080000 cmp=top.niunaijun.blackdexa32/top.niunaijun.blackbox.proxy.ProxyActivity$P0 (has extras)} from uid 10247
12-05 12:48:50.130  1619  6573 I ActivityTaskManager: The Process top.niunaijun.blackdexa32:p0 Already Exists in BG. So sending its PID: 28329
12-05 12:48:50.205  6485 23994 I MediaProvider: Deleted 1 items on external_primary due to top.niunaijun.blackdexa32
12-05 12:48:50.217 28329 28329 W ContextImpl: Failed to ensure /storage/emulated/0/Android/data/com.gtgj.view/cache: java.lang.SecurityException: Invalid mkdirs path: /storage/emulated/0/Android/data/com.gtgj.view/cache does not contain calling package top.niunaijun.blackdexa32
12-05 12:48:50.226 28329 28329 I .blackdexa32:p: The ClassLoaderContext is a special shared library.
12-05 12:48:50.234 28329 28329 W .blackdexa32:p: ClassLoaderContext classpath size mismatch. expected=0, found=3 (PCL[]{PCL[/system/framework/android.test.base.jar*2798937298]#PCL[/system/framework/org.simalliance.openmobileapi.jar*408507849]#PCL[/system/framework/org.apache.http.legacy.jar*3672776127]} | PCL[/data/user/0/top.niunaijun.blackdexa32/virtual/cache/vm.jar*3622534595:/data/user/0/top.niunaijun.blackdexa32/virtual/cache/junit.jar*3930985515:/system/framework/org.apache.http.legacy.jar*3672776127])
12-05 12:48:50.237 28329 28329 W .blackdexa32:p: JIT profile information will not be recorded: profile file does not exist.
12-05 12:48:50.237 28329 28329 W .blackdexa32:p0: type=1400 audit(0.0:2474180): avc: granted { execute } for path="/data/data/top.niunaijun.blackdexa32/virtual/data/app/com.gtgj.view/lib/libblackdex.so" dev="dm-10" ino=357787 scontext=u:r:untrusted_app:s0:c247,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c247,c256,c512,c768 tclass=file app=top.niunaijun.blackdexa32
12-05 12:48:50.401 28329 28329 W top.niunaijun.blackdexa32:p0: Ignoring bad checksum (1121a50b, expected 7fea9ad9)
12-05 12:48:50.549 28329 28329 W .blackdexa32:p0: type=1400 audit(0.0:2474182): avc: granted { execute } for path="/data/data/top.niunaijun.blackdexa32/virtual/data/app/com.gtgj.view/lib/libDexHelper.so" dev="dm-10" ino=612945 scontext=u:r:untrusted_app:s0:c247,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c247,c256,c512,c768 tclass=file app=top.niunaijun.blackdexa32
12-05 12:48:50.634 28329 28329 W .blackdexa32:p: Opening an oat file without a class loader. Are you using the deprecated DexFile APIs?
12-05 12:48:50.776 28329 28329 F libc    : Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xff3adfa8 in tid 28329 (.blackdexa32:p0), pid 28329 (.blackdexa32:p0)
12-05 12:48:50.804 28386 28386 F crash_dump32: crash_dump.cpp:522] failed to attach to thread 28329, already traced by 28374 (top.niunaijun.blackdexa32:p0)
12-05 12:48:50.806 28329 28329 I libc    : debuggerd_signal_handler test : top.niunaijun.blackdexa32:p0
12-05 12:48:50.806 28329 28329 I libc    : debuggerd_signal_handler wait 2 second: top.niunaijun.blackdexa32:p0
12-05 12:48:52.850  1619  3476 I ActivityManager: Process top.niunaijun.blackdexa32:p0 (pid 28329) has died: fg  TOP
12-05 12:48:52.852  1619  3476 I BroadcastQueue: cleanupBroadcastLocked skipPendingBroadcastLocked app = ProcessRecord{409a4bd 28329:top.niunaijun.blackdexa32:p0/u0a247}
12-05 12:48:52.853  1619  3476 I BroadcastQueue: cleanupBroadcastLocked skipPendingBroadcastLocked app = ProcessRecord{409a4bd 28329:top.niunaijun.blackdexa32:p0/u0a247}
12-05 12:48:52.874  1619  1931 I ActivityManager: Start proc 28389:top.niunaijun.blackdexa32:p0/u0a247 for top-activity {top.niunaijun.blackdexa32/top.niunaijun.blackbox.proxy.ProxyActivity$P0}
12-05 12:48:52.888 28389 28389 E .blackdexa32:p: Not starting debugger since process cannot load the jdwp agent.
12-05 12:48:52.940 28389 28389 W .blackdexa32:p: Accessing hidden method Ldalvik/system/VMRuntime;->setHiddenApiExemptions([Ljava/lang/String;)V (blacklist,core-platform-api, reflection, denied)
12-05 12:48:52.941 28389 28389 W .blackdexa32:p: Opening an oat file without a class loader. Are you using the deprecated DexFile APIs?
12-05 12:48:52.941 28389 28389 W .blackdexa32:p: DexFile /data/user/0/top.niunaijun.blackdexa32/code_cache/1638679732940.dex is in boot class path but is not in a known location
12-05 12:48:56.032 24161 24188 I TriggerManager: App resume for long time: top.niunaijun.blackdexa32, reset 1->1
12-05 12:48:57.927 28389 28412 I .blackdexa32:p: Waiting for a blocking GC ProfileSaver
12-05 12:48:57.961 28389 28412 I .blackdexa32:p: WaitForGcToComplete blocked ProfileSaver on ClassLinker for 34.148ms
12-05 12:48:57.973 28389 28402 I .blackdexa32:p: WaitForGcToComplete blocked RunEmptyCheckpoint on ProfileSaver for 11.558ms
12-05 12:49:39.030 24161 24188 I FaceActiveScreen: onRecognitionResult result=0, cost=419, ScreenDim=false, ScreenOn=true, curPkg=top.niunaijun.blackdexa32, curAct=top.niunaijun.blackdex.view.main.MainActivity, isKeyguard=false, isFunOn=true
12-05 12:50:11.186 24161 24188 I TriggerManager: App resume for long time: top.niunaijun.blackdexa32, reset 1->1

**Comment by NorColumba** [comment]
12-05 12:48:50.776 28329 28329 F libc : Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xff3adfa8 in tid 28329 (.blackdexa32:p0), pid 28329 (.blackdexa32:p0)

**Comment by NorColumba** [comment]
样本是com.gtgj.view

**Comment by NorColumba** [comment]
没有给出错误提示，是还能脱吗，我测试下

**Comment by nnjun** [comment]
这个可能是有某种检测
