### ISSUE TITLE
没有一次成功过

### ISSUE THREAD

**Issue by zdongcoding** [CodingGay/BlackDex#6]
**描述错误**
简要说明遇到了什么问题

**重现**
重现该行为的步骤:
1.xxx
2.xxx

**设备信息**
 - 设备: [华为mate30]
 - Android版本: [10]

**运行日志**
请提供运行时所有Logcat日志以便我们排查问题，如果您不是开发者请重现问题之后，提供手机存储：/Download/top.niunaijun.blackdex32(64)_logcat.txt 文件的内容，此内容重启应用将重置，请勿重启应用后才发送。

**其他说明**

**Comment by wukaicheng** [comment]
麻烦上传一下logcat

**Comment by nnjun** [comment]
稍后我进行测试一下，正好有一台30

**Comment by nnjun** [comment]
测试无问题，请问你是自己编译的还是用release的？自己编译的话请先make project一下。

**Comment by nnjun** [comment]
如还有问题请重新open
