### ISSUE TITLE
有些app安装后没有出现在脱壳列表内，是为什么 

### ISSUE THREAD

**Issue by BiteFoo** [CodingGay/BlackDex#60]
**描述错误**
安装blackdex后，进入脱壳列表没有看到安装的应用程序，只有少数的app出现在列表捏

**重现**
重现该行为的步骤:
1.xxx
2.xxx

**设备信息**
 - 设备:  pixel3 
 - Android版本: [10]

**运行日志**
请提供运行时所有Logcat日志以便我们排查问题，如果您不是开发者请重现问题之后，提供手机存储：/Download/top.niunaijun.blackdex32(64)_logcat.txt 文件的内容，此内容重启应用将重置，请勿重启应用后才发送。

**其他说明**

**Comment by nnjun** [comment]
https://github.com/CodingGay/BlackDex/tree/v3.2#%E6%9E%B6%E6%9E%84%E7%89%B9%E5%88%AB%E8%AF%B4%E6%98%8E
