### ISSUE TITLE
脱壳失败

### ISSUE THREAD

**Issue by moonstr** [CodingGay/BlackDex#61]
![Screenshot_20211223_152004_top niunaijun blackdex](https://user-images.githubusercontent.com/31029214/147203693-883e979b-bd91-49ff-bfc1-2a7ec9564b3e.jpg)

**Comment by moonstr** [comment]
目标apk是用360加固的

**Comment by Familyye** [comment]
先安装然后脱

**Comment by moonstr** [comment]
安装过，找不到安装的应用

**Comment by nnjun** [comment]
https://github.com/CodingGay/BlackDex#%E6%9E%B6%E6%9E%84%E7%89%B9%E5%88%AB%E8%AF%B4%E6%98%8E
