### ISSUE TITLE
爱加密脱壳失败

### ISSUE THREAD

**Issue by coremodmc** [CodingGay/BlackDex#66]
测试伪爱加密和爱加密均无法脱壳
伪爱加密可以通过关闭Hook dump来脱壳，但脱出来的是残废dex，无法正常运行
爱加密无法通过调整hook dump与深度脱壳来进行脱壳，BlackDex64会直接闪退，BlackDex32会卡死一会后报错

设备使用: Samsung Galaxy S10
Android: OneUI 3.1 , Android 11
包: com.sfacg
[日志文件](https://gist.github.com/3JoB/aef9333b14f7520bfc2a42fdfd72c9a3)

**Comment by nnjun** [comment]
目前本项目已经被加固做了对抗。
