### ISSUE TITLE
无法脱360？

### ISSUE THREAD

**Issue by wudao22** [CodingGay/BlackDex#67]
**在此写下你的问题**
![Screenshot_2022-03-01-11-25-42-356_bin.mt.plus.jpg](https://user-images.githubusercontent.com/78141936/156099120-0f307f4f-41d8-40ac-8b0b-f958fc51cccc.jpg)

**Comment by xiaoyaomeng** [comment]
很高兴收到您的邮件，看到后将立即回复~Thank you~

**Comment by nnjun** [comment]
目前本项目已经被加固做了对抗。
