### ISSUE TITLE
通付盾，爱加密脱壳失败

### ISSUE THREAD

**Issue by wgetnz** [CodingGay/BlackDex#7]
通付盾，爱加密脱壳失败
样本下载地址：

链接：https://pan.baidu.com/s/1ywJNYWptvk1ZDvIcRM25Cg 
提取码：wehx 
复制这段内容后打开百度网盘手机App，操作更方便哦--来自百度网盘超级会员V4的分享

另外小米6 MIUI11.0.5 android9会提示dex not found

**Comment by nnjun** [comment]
一些支付、银行等应用均有反虚拟环境的操作。可能是无法被虚拟化起来导致无法进行脱壳。
