### ISSUE TITLE
360加固最新的脱不了

### ISSUE THREAD

**Issue by LoveDoLove** [CodingGay/BlackDex#71]
求大大能更新小的需要

**Comment by Familyye** [comment]
自己可以随便改改特征就好了

**Comment by owen800q** [comment]
@Familyye  可以分享下比方说哪些特征要改或者被检测到吗？

**Comment by Familyye** [comment]
检测的是包名

**Comment by ruancw** [comment]
@owen800q 同问，有解决嘛

**Comment by 332455590** [comment]
> 
@owen800q
求指教， 大佬稍微告诉下关键字，苦恼中...

**Comment by owen800q** [comment]
@332455590  @ruancw 這個已經完全被和諧了，如何改都過不了檢測

**Comment by 332455590** [comment]
@owen800q 有其他的什么手段没，我准备试试frida

**Comment by FangPengbo** [comment]
> @owen800q有其他的什么手段没，我准备试试frida

frida可以脱吗

**Comment by ray-yuruisoft** [comment]
frida只提供hook的动态库，还要自己找函数自己hook?现在还有没有那种一键式的啊~
