### ISSUE TITLE
打开软件后，应用列表中找不到要脱壳的app

### ISSUE THREAD

**Issue by scjzhong** [CodingGay/BlackDex#79]
打开软件后，应用列表中找不到要脱壳的目标app

**Comment by Y-1918** [comment]
1、你的目标app 是多少位的
2、你安装的blackdex是多少位的

64位的app，装32位的blackdex当然找不到目标应用，要安装对应的blackdex。

**Comment by scjzhong** [comment]
谢谢，脱壳后在指定目录找不到文件是？

**Comment by scjzhong** [comment]
谢谢
