### ISSUE TITLE
带有root环境检测的app

### ISSUE THREAD

**Issue by FuYu520** [CodingGay/BlackDex#83]
大佬，请问那些含有root环境检测的app，脱壳都会失败嘛，我试了一个，脱壳失败了，使用的是以前的去年的360加固
，算是比较老了，我不确定是环境检测的问题还是360的问题，且我试了很多个32位的全部脱壳失败

**Comment by xiaoyaomeng** [comment]
很高兴收到您的邮件，看到后将立即回复~Thank you~
