### ISSUE TITLE
无法脱壳

### ISSUE THREAD

**Issue by Ebzzel** [CodingGay/BlackDex#87]
**描述错误**
未知错误

**重现**
重现该行为的步骤:
1.xxx
2.xxx

**设备信息**
 - 设备: [Redmi K50]
 - Android版本: [12]

**运行日志**
请提供运行时所有Logcat日志以便我们排查问题，如果您不是开发者请重现问题之后，提供手机存储：/Download/top.niunaijun.blackdex32(64)_logcat.txt 文件的内容，此内容重启应用将重置，请勿重启应用后才发送。

**其他说明**

**Comment by xiaoyaomeng** [comment]
很高兴收到您的邮件，看到后将立即回复~Thank you~
